version: "3.8"
services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: doanyte
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  backend:
    build: ./BackEnd
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/doanyte?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      DOCKER_ENV: "true"
    ports:
      - "8080:8080"
    volumes:
      - backend_static:/app/static
    restart: unless-stopped
    networks:
      - backend_network

volumes:
  mysql_data:
  backend_static:

networks:
  backend_network:
    driver: bridge


